twilio/twilio-webrtc.js

.release.json
.travis.yml
package.json

Setup @twilio/webrtc to use release-tool

---

lib/rtcpeerconnection/firefox.js
package.json

JSDK-1503 RTCSessionDescription's props are now read-only in Firefox.

---

CHANGELOG.md
lib/getusermedia.js

Reject getUserMedia on platforms that lack support

---

CHANGELOG.md
lib/getstats.js
lib/rtcpeerconnection/firefox.js

@manjeshbhargav Fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1405893

Don't create so many MediaStreams

---

CHANGELOG.md
README.md
lib/rtcpeerconnection/chrome.js
lib/rtcpeerconnection/firefox.js
lib/rtcpeerconnection/safari.js
lib/util/index.js
test/integration/spec/rtcpeerconnection.js
test/lib/fakestats.js

@manjeshbhargav @ryan-rowland please take a look.

Add support for maxPacketLifeTime

---

CHANGELOG.md
lib/getstats.js
test/lib/fakestats.js

@manjeshbhargav mind taking a look? This is a pretty small change, with tests, so I plan to release today.

JSDK-1605: Fix getStats bug

---

CHANGELOG.md
README.md
lib/rtcpeerconnection/chrome.js
lib/rtcpeerconnection/firefox.js
lib/rtcpeerconnection/safari.js
lib/rtcrtpsender.js
lib/rtcrtpsender/chrome.js
package.json
test/integration/spec/rtcpeerconnection.js

@markandrus 
I've added a commit for each ticket (roughly). Any feedback is really helpful.
I'll add another commit refactoring the README to remove any issues that we worked around
on before this refactor.

WebRTC 1.0 Migration

---

CHANGELOG.md
test/integration/spec/rtcpeerconnection.js

Prepare for 2.0.0 rc1

---

lib/rtcpeerconnection/chrome.js

Change default for Chrome RTCPeerConnection to "plan-b"

---

CHANGELOG.md
README.md
karma/makeconf.js
lib/rtcpeerconnection/chrome.js
lib/rtcpeerconnection/firefox.js
lib/rtcpeerconnection/safari.js
package.json
test/integration/spec/rtcpeerconnection.js

Actually call removeTrack

---

.travis.yml
karma/makeconf.js
test/integration/spec/getstats.js
test/lib/util.js

I've opened this against `support-2.1.x` so that we get the change when we merge back to `master`.

Fix Chrome tests on Travis

---

README.md
lib/rtcpeerconnection/firefox.js
test/integration/spec/rtcpeerconnection.js
test/lib/detectsilence.js

I didn't update CHANGELOG.md in this PR, since, I figure, once twilio-webrtc.js@2.1.2 is out, we can just paste that CHANGELOG.md entry into this branch.

Bug 1480277 3.x

---

test/integration/spec/rtcpeerconnection.js

Hey y'all, I've added some tests for `addTransceiver`. Since we may soon start using this in twilio-video.js, we ought to prepare to consume this from twilio-webrtc.js. It doesn't look like we need any shims for Firefox right now, but we may need some in Chrome. Not sure yet. **EDIT:** Chrome seems OK so far 👍

Add `addTransceiver` tests

---

CHANGELOG.md
README.md
lib/rtcpeerconnection/chrome.js
test/integration/spec/rtcpeerconnection.js

JSDK-2164 Removing workaround for Chrome's "ontrack" bug.

---

CHANGELOG.md
README.md
lib/rtcpeerconnection/chrome.js
package.json
test/integration/spec/rtcpeerconnection.js

@markandrus Continued from: https://github.com/twilio/twilio-webrtc.js/pull/52.

JSDK-2146 Removing workaround for bug: https://bugs.chromium.org/p/chromium/issues/detail?id=774303.

---

lib/edgestats.js

This is an attempt to fix `twilio-video` build failures in phantom js browser. @manjeshbhargav

Lazy instantiate WeakMap in edgestats

---

lib/rtcpeerconnection/safari.js

JSDK-2224: Firefox to Safari failing to stream video

---

lib/getstats.js
test/integration/spec/getstats.js
test/lib/fakestats.js
test/unit/spec/getstats.js

Reference: https://www.chromestatus.com/feature/5665052275245056
@manjeshbhargav Moved to spec complaint getStats for Chrome. Please review

Use WebRTC 1.0 compliant getStats() for Chrome

---

CHANGELOG.md

Prep for 3.2.0-rc1

---

CHANGELOG.md
README.md
karma/makeconf.js
lib/rtcpeerconnection/safari.js
package.json
test/integration/spec/rtcpeerconnection.js

JSDK-2231 Supporting Unified Plan SDPs on Safari 12.1

---

lib/getstats.js
test/integration/spec/getstats.js
test/lib/fakestats.js
test/lib/util.js
test/unit/spec/getstats.js

Cherry-picked implementation from `safari-stats` branch. @manjeshbhargav

Implement getstats for Safari browser

---

CHANGELOG.md

Prep for 3.2.0-rc4

---

lib/rtcpeerconnection/safari.js
test/integration/spec/getstats.js
test/integration/spec/rtcpeerconnection.js

createOffer() now generates "recvonly" audio/video m= lines only if no RTCRtpSenders are available.

Safar 12.1 createOffer() refactor.

---

lib/rtcpeerconnection/safari.js
test/integration/spec/getstats.js
test/integration/spec/rtcpeerconnection.js

createOffer() now generates "recvonly" audio/video m= lines only if no RTCRtpSenders are available.

---

CHANGELOG.md

Prep for 3.2.0.

---

CHANGELOG.md

Prep for 2.2.0.

---

CHANGELOG.md
karma/makeconf.js
lib/getstats.js
lib/mediastream.js
lib/rtcpeerconnection/chrome.js
lib/rtcpeerconnection/firefox.js
lib/rtcpeerconnection/safari.js
lib/util/index.js
lib/util/sdp.js
test/integration/spec/getstats.js
test/integration/spec/rtcpeerconnection.js

* Removing plan-b enforcement in ChromeRTCPeerConnection.
* Using getSdpFormat() in SafariRTCPeerConnection.
* Disabling autoplay policy in Firefox 66+ for tests.

JSDK-2265 Using default SDP format.

---

lib/rtcpeerconnection/safari.js

Same as #93 for `support-2.x` branch.

JSDK-2286 for support-2.x

---

CHANGELOG.md

Prep for 4.0.0-rc2.

---

CHANGELOG.md
lib/getstats.js
lib/rtcpeerconnection/chrome.js
lib/util/sdp.js
test/integration/spec/rtcpeerconnection.js

* JSDK-2312 - Support unified plan on Chrome 72+
* JSDK-2303 - Convert audioLevel range to 0-32767

JSDK-2312, JSDK-2303

---

CHANGELOG.md
README.md
lib/getstats.js
lib/rtcpeerconnection/chrome.js
lib/rtcpeerconnection/firefox.js
lib/rtcpeerconnection/safari.js
lib/util/sdp.js
test/integration/spec/rtcpeerconnection.js

* JSDK-2313 - Enable unified plan support for Chrome.
* JSDK-2318 - Convert audioLevel fron 0-1 to 0-32767.

JSDK-2313, JSDK-2318

---

.travis.yml
CHANGELOG.md

prepping for release of 2.4.0. This release is required dependency for twilio-video@1.2.0 release.  

prep for release 2.4.0

---

CHANGELOG.md

updated changelog for releasing rc.1 

update changelog in preparation for 4.1.3-rc.1

---

test/integration/spec/rtcpeerconnection.js

JSDK-2639 Updating tests to not expect "signalingstatechange" event when calling RTCPeerConnection.close() for Chrome 81+.

[Chrome 81+] RTCPeerConnection.close() does not emit "signalingstatechange".

---

.circleci/config.yml
.circleci/runbuild.js
karma/makeconf.js
package.json

This change creates a circleci config to run the tests. Changes are mostly borrowed from twilio-video repo.

use circleci for integration tests

---

CHANGELOG.md

changelog update for video_4654

---

CHANGELOG.md
lib/getstats.js
test/unit/spec/getstats.js

VIDEO-4718 Reporting metrics related to a/v sync.

---

CHANGELOG.md
lib/getstats.js
test/unit/spec/getstats.js

VIDEO-3600 | Fix a bug where audioLevel, frameRate, and captureDimensions are null

---

CHANGELOG.md

Pointing changelog credits to correct user and adding github pr link

Fixing GitHub Tag 

---

CHANGELOG.md

Prepping CHANGELOG for 4.6.0 release

Prep for 4.6.0 release
