twilio/twilio-webrtc.js

- test/integration/spec/rtcpeerconnection.js
The fix has landed, so we should be able to reenable this.
> Reenable "track" event test with adapter.js

- CHANGELOG.md
- lib/rtcpeerconnection/chrome.js
- lib/rtcpeerconnection/safari.js
- lib/rtcsessiondescription/chrome.js
- test/integration/spec/rtcsessiondescription.js
@markandrus 
Continuing from here: https://github.com/manjeshbhargav/twilio-webrtc.js/pull/1
Fixed the tests.
> JSDK-1503 RTCSessionDescription's properties are now read-only.

- README.md
- karma/makeconf.js
- lib/rtcpeerconnection/chrome.js
- package.json
@markandrus 
This PR contains changes to accommodate `addTrack/removeTrack/ontrack`. A new Karma Chrome launcher has been added with the flag `--enable-blink-features=RTCRtpSender`.
I had to bump up the minimum version of `webrtc-adapter` to `5.0.6` as there were some bugs in `5.0.3` in its `addTrack` shim which was causing our tests to fail.
> Adding Karma Chrome launcher for WebRTC 1.0 (addTrack/removeTrack).

- CHANGELOG.md
- README.md
- lib/getstats.js
- test/integration/index.js
- test/integration/spec/getstats.js
- test/lib/fakestats.js
- test/lib/util.js
- test/unit/spec/getstats.js
@markandrus 
This PR adds support for `getStats()` to return stats for the active RTCIceCandidate pair.
TODO:
=====
Integration tests
> Active RTCIceCandidate pair stats.

- lib/rtcpeerconnection/chrome.js
In Chrome, the RTCPeerConnection constructor accepts a second argument. It's not specced in Web IDL, AFAICT, but in the C++, it's some instance of `webrtc::MediaConstraintsInterface`. So I've called it `constraints` here. This parameter allows specifying some Chrome-specific settings, such as those specified by Google Hangouts. For example,
```js
new RTCPeerConnection(configuration, {
mandatory: {
googCpuOveruseDetection: true,
googCpuOveruseThreshold: 85,
googCpuUnderuseThreshold: 55
}
});
```
I would like us to add support for `constraints` so that libraries like twilio-video.js can experiment with these options.
> Allow passing Chrome-specific constraints

- CHANGELOG.md
- package.json
@manjeshbhargav I changed 2.0.1 to 2.1.0 because we actually have new features, therefore we must bump the minor version number.
> Prepare for 2.1.0

- CHANGELOG.md
- lib/rtcpeerconnection/chrome.js
- test/integration/spec/rtcpeerconnection.js
It took a bit of digging, but I realized the crash in JSDK-2032 was due in part to the fact that we do not perform the "SSRC fix" in `createAnswer`, only `createOffer`. For context: the "SSRC fix" involves overwriting SSRCs generated by the RTCPeerConnection such that, no matter how many times you call `createOffer`/`createAnswer` (irrespective of `setLocalDescription`), the same SSRCs will be used. Why do we want to do this? Well, Chrome can act weirdly when SSRCs are changed (it may raise a new MediaStreamTrack upon SSRC change for example). See [here](https://bugs.chromium.org/p/webrtc/issues/detail?id=5208) and [here](https://bugs.chromium.org/p/webrtc/issues/detail?id=1817) for related bugs.
Anyway, my (difficult to test) hypothesis is that our failure to fix up the SSRC …
> Fix up SSRCs in createAnswer, not just createOffer

- lib/getstats.js
- test/unit/spec/getstats.js
@manjeshbhargav @markandrus 
Please review the PR while I am looking into one of the integration test failures in firefox.
> JSDK-1227: Fix getStats api deprecated warnings in firefox

- .travis.yml
- karma/makeconf.js
- lib/rtcpeerconnection/chrome.js
- lib/util/sdp.js
- test/integration/spec/rtcpeerconnection.js
Goal is to run integration tests twice in Chrome when `sdpSemantics` is supported (once for "plan-b" and once for "unified-plan"); however, I hit a "too many RTCPeerConnections" error due to our numerous tests, so I'm still working on that. **EDIT:** I worked around it by exposing `gc`.
> Expanded Unified Plan Support

- CHANGELOG.md
- README.md
- karma/makeconf.js
- lib/rtcpeerconnection/chrome.js
- lib/rtcpeerconnection/firefox.js
- lib/rtcpeerconnection/safari.js
- package.json
- test/integration/spec/rtcpeerconnection.js
- test/lib/detectsilence.js
This reverts the accidental merge commit and then lands the Bug 1480277-related changes. It's probably best to review by comparing `2.1.1` to this branch. For example, [see here](https://github.com/twilio/twilio-webrtc.js/compare/2.1.1...bug-1480277-2.x).
> Bug 1480277 2.x

- CHANGELOG.md
- lib/rtcpeerconnection/firefox.js
- test/integration/spec/rtcpeerconnection.js
@manjeshbhargav I'm exploring some changes on the 1.x branch of twilio-video.js. They're still unreleased, but the most recent work is happening here: https://github.com/twilio/twilio-video.js/pull/406 I want to use `addTransceiver`, but the 2.x version of this shim needs the following change to support it. 3.x version of this shim does not.
> Firefox: Calling addTransceiver should update getSenders

- karma/makeconf.js
- lib/getstats.js
- lib/rtcpeerconnection/edge.js
- lib/rtcpeerconnection/index.js
- lib/util/index.js
- package.json
- test/integration/spec/getstats.js
- test/integration/spec/rtcpeerconnection.js
I fixed most of the integration tests on Edge. @markandrus @manjeshbhargav There are still couple of integration test failures that need fix.
1. `#TrackEvent`  failing with InvalidState Error
2. All `rollback` sdp type tests.
> Introduce RTCPeerConnection Shim for Edge 

- lib/edgestats.js
- lib/getstats.js
@markandrus @manjeshbhargav 
Edge implementation of stats was logging following warning/error:
`possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit`
This PR is an attempt to fix the leak. Please review.
> Fix EventEmitter memory leak in Edge's getstats implementation

- CHANGELOG.md
- lib/getstats.js
- test/integration/spec/getstats.js
- test/lib/util.js
This fixes the failing `getStats` integration tests for Firefox 65.
> JSDK-2235 Consuming spec-compliant RTCIceCandidateStats from Firefox 65 onwards.

- CHANGELOG.md
@syerrapragada
I copied the CHANGELOG.md entries for 2.1.4 since it was cut from a support branch.
> Prep for 2.2.0-rc2.

- CHANGELOG.md
- README.md
- lib/rtcpeerconnection/chrome.js
A customer [reported](https://github.com/twilio/twilio-video.js/issues/507) that Electron 2.x was broken by `twilio-video.js@1.15.0`. The reason for this is that while adding support for Unified Plan, we removed the workaround for this Chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=774303) which is still present in Electron 2.x. So, this PR adds the workaround back **only for Plan-B ChromeRTCPeerConnection**.
> JSDK-2266 Adding back workaround for Chrome 63- RTCTrackEvent bug to support Electron 2.x.

- lib/rtcpeerconnection/chrome.js
- test/integration/spec/rtcpeerconnection.js
Starting from Chrome 73, calling `createOffer()` a second time without calling `setLocalDescription()` on the first offer will change the mids of those RTCRtpTransceivers that have not yet been fully negotiated (gone through an offer --> answer cycle).
So, this PR calls `setLocalDescription()` on the current offer before calling `createOffer()` a second time.
> JSDK-2219 Chrome 73+: Lock in mids by calling setLocalDescription() before createOffer()

- lib/getstats.js
- test/integration/spec/getstats.js
- test/integration/spec/rtcpeerconnection.js
- test/unit/spec/getstats.js
@syerrapragada ,
In order to support Electron 2.x and 3.x, we need to use Chrome's legacy getStats(). This PR re-introduces it for Chrome versions < 67, which cover both Electron versions.
> JSDK-2267 Adding Chrome legacy getStats() support in order to support Electron 2.x and 3.x.

- CHANGELOG.md
- karma/makeconf.js
We have to bump up the major version here because this is not compatible with earlier 2.x beta versions of twilio-video.js, especially because plan-b enforcement is removed.
> Prep for 4.0.0-rc1.

- lib/rtcpeerconnection/safari.js
- test/integration/spec/rtcpeerconnection.js
Since our current shim is based on RTCRtpSenders, it ends up creating the "offerToReceive" RTCRtpTransceivers as soon as there are no MediaStreamTracks of a particular kind present in the RTCPeerConnection. In order to work around this, we only create "offerToReceive" RTCRtpTransceivers if there are no existing RTCRtpTransceivers with non-null RTCRtpReceiver tracks.
> JSDK-2286 Refactoring "offerToReceive" shim for "unified-plan" Safari.

- CHANGELOG.md
- lib/rtcpeerconnection/chrome.js
- lib/util/sdp.js
* Enforcing "plan-b" SDP format in Chrome
* Retaining "unified-plan" SDP format support for Safari 12.1+.
> JSDK-2306 Enabling unified plan only for Safari 12.1+

- CHANGELOG.md
- lib/rtcpeerconnection/chrome.js
- lib/util/sdp.js
* Enforcing "plan-b" SDP format for Chrome
* Retaining "unified-plan" SDP format support for Safari 12.2+
> JSDK-2305 Enabling unified plan only for Safari 12.2+

- karma/makeconf.js
- package.json
To run electron tests on this repo, previously we used a fork of karma-electron (https://github.com/twilio/karma-electron) that added a new flag to disable custom user agent. 
Our change is now accepted and merged (https://github.com/twolfson/karma-electron/pull/39) into upstream repo we no more need to maintain our fork. This change takes a direct dependency on upstream repo to enable retiring our fork.
verified that electron tests passed after the change. 
```
BROWSER=electron npm run test:integration
...
Electron 5.0.0 (Mac OS X 10.14.5): Executed 289 of 298 (skipped 9) SUCCESS (2.803 secs / 0.204 secs)
TOTAL: 289 SUCCESS 
```
Similar change in: https://github.com/twilio/twilio-video.js/pull/652
> update karma-electron dependency and flag

- lib/rtcpeerconnection/chrome.js
- lib/util/sdp.js
@makarandp0 
This PR adds a flag "sdpSemantics" to the function for calculating sdp format. This allows us to easily switch between plan-b and unified-plan using ConnectOptions (separate PR coming for that). This also solves JSDK-2392 (PeerConnection being created when the SDK is loaded). Now, we don't have to maintain `master-chrome-planb` branch anymore.
> Add sdpSemantics flag

- .travis.yml
- CHANGELOG.md
- lib/rtcpeerconnection/chrome.js
- lib/rtcpeerconnection/safari.js
@makarandp0 
This PR is part of fixing [JSDK-2463](https://issues.corp.twilio.com/browse/JSDK-2463). We maintain a mapping of Track IDs and SSRCs to make sure that the same SSRCs appear for a given Track ID over multiple SDPs. Now, we make sure that the update applied to this map is undone when an SDP is rolled back.
> JSDK-2463 Undoing the updates made to "_tracksToSSRCs" when a "rollback" SDP is applied.

- CHANGELOG.md
- lib/rtcpeerconnection/chrome.js
- lib/rtcpeerconnection/safari.js
- test/integration/spec/rtcpeerconnection.js
> JSDK-2522 Retain rolled back tracks to SSRCs Map when setLocalDescription() is called immediately after a rollback.

- lib/rtcpeerconnection/index.js
- lib/rtcsessiondescription/firefox.js
when RTCPeerConnection or RTCSessionDescription is not available, (Happens in Firefox when `media.peerconnection.enabled` is set to `false` from `about:config`)  loading this module ends up with errors. 
This change avoids those undefined references.
> JSDK-2591: do not dereference undefined

- CHANGELOG.md
- lib/getstats.js
- lib/util/index.js
- test/unit/index.js
- test/unit/spec/util/index.js
@makarandp0 
This PR has the following changes:
* Make sure Chrome and Firefox are detected correctly on iOS.
* Consolidate browser version detection in guessBrowserVersion().
> JSDK-2670 Handle Chrome and Firefox iOS user agents.

- lib/getstats.js
- test/integration/spec/getstats.js
- test/unit/spec/getstats.js
- JSDK-2755, JSDK-2780 - update stat gathering to include stats from `remote-inbound-rtp` and `remote-output-rtp` - because that's  where you find packets_lost, roundTripTime for local tracks
- JSDK-2787 - update roundTripTime to be in int (in milliseconds) and not double (in seconds)
> JSDK-2755: get more localtrack stats

- .travis.yml
- lib/getstats.js
- scripts/travis-run-tests.sh
- test/integration/spec/rtcpeerconnection.js
- test/unit/spec/getstats.js
Changes:
- Chrome change (to not emit `singalingstatechange` when closed) was [reverted](https://bugs.chromium.org/p/chromium/issues/detail?id=1060547), and it would [go back](https://bugs.chromium.org/p/chromium/issues/detail?id=699036) in 83+. Updated tests to match the behavior. Updated them also for Safari and Firefox to match observed behavior.
- Fixed dpkg [error](https://askubuntu.com/questions/1065231/dpkg-deb-error-archive-has-premature-member-control-tar-xz-before-contr) by updating `dpkg`
- Fixed [insights error JSDK-2826](https://issues.corp.twilio.com/browse/JSDK-2826) caused by some Safari Mobile clients sending `inprogress` for `activeCandidatePairStats.state`.  We will now update it to `in-progress`   
> All third-party contributors acknowledge …
> JSDK-2799: fix test expectations

- .circleci/config.yml
- .release.json
- package.json
This PR works with https://github.com/twilio/release-tool/pull/2 to allow release_tool to release builds using circleci
> add circleCI workflow to release builds

- CHANGELOG.md
- lib/getusermedia.js
- lib/index.js
- lib/mediastream.js
- lib/mediastreamtrack.js
- lib/rtcicecandidate.js
- lib/rtcpeerconnection/index.js
- lib/rtcsessiondescription/firefox.js
- lib/rtcsessiondescription/index.js
- lib/util/index.js
@makarandp0 
This PR makes sure we stop supporting Chrome (23 - 55) and Firefox (22 - 43) versions that support only the prefixed `webkit` and `moz` WebRTC APIs that are now deprecated.
> JSDK-2832 Stop supporting prefixed WebRTC APIs.

- test/integration/spec/rtcpeerconnection.js
chrome 85+ no longer sends signalingStateChange when `peerConnnection.close()` is called. update the expectation for these versions.
Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=699036&q=signalingstatechange&can=2
chrome tests now pass: https://app.circleci.com/pipelines/github/twilio/twilio-webrtc.js/41/workflows/cf6aca0b-9234-4903-bf1f-1f999b8e566e
> update expectSinglingStateChangeOnClose for chromeVersion >= 85

- CHANGELOG.md
- lib/getstats.js
@makarandp0 
This PR makes sure es5 support is preserved by converting `const` references (introduced in #119) to `var`.
> JSDK-2913 Preserve es5 support

- CHANGELOG.md
- lib/getstats.js
- test/unit/spec/getstats.js
when simulcast is enabled on chrome 84 returns multiple outbound-rtp stats for the given track. Previously we were just returning stats from last outbound-rtp stats found. This change consolidates the stats for bytesSent, packetsSent, packetsLost 
> JSDK-2920: consolidate RTP stats when multiple found

- .gitignore
- lib/util/index.js
- test/integration/spec/rtcpeerconnection.js
We had some code that overrides all functions on given type. To find functions it used something like:
```
for (var methodName in source) {
if ('function' === typeof source[methodName]) {
// override it....
}
}
```
But this code ends up evaluating all properties of the object. and any property that returns a promise (like `RTCPeerConnection.peerIdentity` does), we do not handle rejection of those promises, causing the browser to complain.
This simple fix, avoids the type check on properties. It may be possible to remove the type check completely, but I am keeping it just to be safe. 
> VIDEO-4654: do not call property getters

- lib/rtcpeerconnection/chrome.js
- lib/rtcpeerconnection/safari.js
- lib/util/index.js
Small PR which addresses iOS Chrome's inability to subscribe to a track. I've simply moved over what we currently have implemented for Safari into the chrome tab as well as removed some of the legacy properties we looked at which are not supported by Safari.
> addTransceiver for iOS Chrome

- CHANGELOG.md
- lib/util/index.js
- test/unit/spec/util/index.js
JIRA: [VIDEO-8374](https://issues.corp.twilio.com/browse/VIDEO-8374)
[WKWebView Testing Notes](https://docs.google.com/document/d/1suzE2m6MAV-qXyqcLR7NGTf09ZtGDWVsa5GUMDa4tyA/edit#)
This small PR is for adding support for WKWebView to the SDK.
> VIDEO-8374 - Support for WKWebView/SFSafariViewController
